//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HensFarmsEntities : DbContext
    {
        public HensFarmsEntities()
            : base("name=HensFarmsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Farm> Farms { get; set; }
        public virtual DbSet<HouseData> HouseDatas { get; set; }
        public virtual DbSet<House> Houses { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
